export const toolList = [
  { name: "Epoch Timestamp To Date", href: "/tools/epoch-to-date" },
  { name: "XML to JSON Converter", href: "/tools/xml-to-json" },
  { name: "JSON to XML Converter", href: "/tools/json-to-xml" },
  { name: "CSV to JSON Converter", href: "/tools/csv-to-json" },
  { name: "CSV to XML Converter", href: "/tools/csv-to-xml" },
  { name: "YAML to JSON Converter", href: "/tools/yaml-to-json" },
  { name: "JSON to YAML Converter", href: "/tools/json-to-yaml" },
  { name: "JSON Formatter", href: "/tools/json-formatter" },
  { name: "Text Case Converter", href: "/tools/text-case-converter" },
  { name: "Base64 Encoder/Decoder", href: "/tools/base64-encoder-decoder" },
  { name: "JWT Decoder", href: "/tools/jwt-decoder" },
  { name: "URL Encoder/Decoder", href: "/tools/url-encoder-decoder" },
  { name: "HTML Entities Encoder/Decoder", href: "/tools/html-entities" },
  { name :"UUID Generator", href: "/tools/uuid-generator" },
  { name: "SHA256 / MD5 Hash Generator", href: "/tools/hash-generator" },
  { name :"Text Diff Checker", href: "/tools/text-diff-checker" },
  { name :"String / Word Counter", href: "/tools/string-word-counter" },
  { name :"Regex Tester", href: "/tools/regex-tester" },
  { name :"Color Converter", href: "/tools/color-converter" },
  { name: "Number Base Converter", href: "/tools/number-base-converter" },
  { name: "Age Calculator", href: "/tools/age-calculator" },
  { name: "Typing Practice", href: "/fun/typing-practice" },
  { name :"PX to REM & REM to PX Converter", href: "/tools/px-rem-converter" },
  { name: "PX to EM & EM to PX Converter", href: "/tools/px-em-converter" },
];
