export const toolList = [
  { name: "Epoch Timestamp To Date", href: "/tools/epoch-to-date" },
  { name: "XML to JSON Converter", href: "/tools/xml-to-json" },
  { name: "JSON to XML Converter", href: "/tools/json-to-xml" },
  { name: "CSV to JSON Converter", href: "/tools/csv-to-json" },
  { name: "CSV to XML Converter", href: "/tools/csv-to-xml" },
  { name: "YAML to JSON Converter", href: "/tools/yaml-to-json" },
  { name: "JSON to YAML Converter", href: "/tools/json-to-yaml" },
  { name: "Text Case Converter", href: "/tools/text-case-converter" },
  { name: "Base64 Encoder/Decoder", href: "/tools/base64-encoder-decoder" },
  { name: "JWT Decoder", href: "/tools/jwt-decoder" },
  { name: "URL Encoder/Decoder", href: "/tools/url-encoder-decoder" },
  { name: "Hex to Decimal Converter", href: "/tools/hex-to-decimal" },
  { name: "Decimal to Hex Converter", href: "/tools/decimal-to-hex" },
  { name: "Binary to Decimal Converter", href: "/tools/binary-to-decimal" },
  { name: "Decimal to Binary Converter", href: "/tools/decimal-to-binary" },
];
